# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4)),
                ('semester', models.CharField(choices=[('SP', 'Spring'), ('SU', 'Summer'), ('FA', 'Fall'), ('WI', 'Winter')], max_length=2)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.Application')),
            ],
        ),
    ]
