# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20170108_0102'),
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='circle_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='session.Circles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='year',
            field=models.IntegerField(),
        ),
    ]
