# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20170108_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='circle_name',
            new_name='circle_uid',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='user_id',
            new_name='user',
        ),
    ]
