# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circles',
            fields=[
                ('circle_name', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('circle_uid', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='circle_staff',
            field=models.ManyToManyField(to='session.Circles'),
        ),
    ]
